# Generated by Django 2.1.10 on 2019-07-29 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postioapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postioapp',
        ),
    ]
