# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-01 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postioapp', '0002_delete_postioapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_title', models.CharField(max_length=300)),
                ('profile_image', models.ImageField(blank=True, upload_to=b'')),
                ('profile_body', models.TextField(max_length=500)),
            ],
        ),
    ]
