# Generated by Django 2.1.10 on 2019-08-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postioapp', '0004_auto_20190801_1859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
