# Generated by Django 2.1.10 on 2019-08-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='c_author',
        ),
        migrations.RemoveField(
            model_name='license',
            name='l_author',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='p_author',
        ),
    ]
