# Generated by Django 2.1.10 on 2019-08-08 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myprofile', '0004_portfolio_p_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='l_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_license', to=settings.AUTH_USER_MODEL),
        ),
    ]
